server:
  port: 8087


spring:
  application:
    name: springbootgraphql
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:graphql/**/


  data:
    mongodb:
      host: localhost
      port: 27017
      database: test



#logging:
#  level:
#    ROOT: ERROR